### ISSUE TITLE
Logotype design

### ISSUE THREAD

**Issue by zuurw** [HikwaMehluli/Polaroid-Image-Gallery#1]
Hello @HikwaMehluli , Im a Graphic Designer that likes to contribute to open source projects, can you tell me more about Polaroid-Image-Gallery? I like very much everything about Polaroid, so if you want it will be a pleasure to me to design a logo for this project.

If you want just tell me what you want for the logo?

Greetings.

**Comment by HikwaMehluli** [comment]
Hi @zuurw thanks for showing interest in my small project. A logo would be nice, once I get this project to be a plugin of some sort. Basically Polaroid is an image display gallery, which I foresee making it into a WordPress Plugin and eventually do plugins for other CMS platforms, plus social media intergation like using Instagram especially. 

If you would like to create a logo, please do. This is an open source project and community as long as you agree  with terms Yes Please Do.

**Comment by zuurw** [comment]
Hi @HikwaMehluli, I will start today working in your logo, do you have any request for the logo, like colors or something more specific?

Greetings.

**Comment by HikwaMehluli** [comment]
Go all in on what ever you think is cool - thats the beauty about open source. As long as its super unique.

**Comment by zuurw** [comment]
Hi, I've been creating some designs for your project, so let me explain the concept:

Initially I created three polaroid photos and put a pointing finger, to give the feeling that you are going through the photo gallery.

The second concept basically was to put the three polaroid photos inside a folder, like a photo gallery folder and also put the pointing finger with the same intention described above.

Finally the third concept was to turn the folder into a polaroid camera.

I do not know if you like any of these designs I created, if you want I can create other design or change the colors.

I'll wait for your feedback.

Cheers!

![logo proposal polaroid](https://user-images.githubusercontent.com/40801473/42281088-7049973c-7f9a-11e8-8b0e-801fde296af7.png)

**Comment by HikwaMehluli** [comment]
Colors are amazing and all concepts wonderful. Really amazing.

If I had to choose I think pointing finger #3 is the best

**Comment by zuurw** [comment]
Hi @HikwaMehluli , Im happy that you like it, is this the one that you want?, What colors do you want for the text?

Cheers!

![logo3](https://user-images.githubusercontent.com/40801473/42282139-7376e18c-7f9d-11e8-8764-5ac02af795c9.png)

**Comment by HikwaMehluli** [comment]
@zuurw The ideal one is the first row number 3.

**Comment by nunojesus** [comment]
Hi, Im going to create the files and make a pull request. What type of files do you want? Png and svg ? 
cheers!

**Comment by HikwaMehluli** [comment]
@nunojesus png, I have just updated and used @zuurw logo but needed him to do pull request so he gets his contributor status

**Comment by nunojesus** [comment]
Sorry but this is not the project that Im working, wrong repository, @HikwaMehluli can you delete my name reference in your comment I will delete my  comments too. Sorry to you and too @zuurw that made an amazing work.

**Comment by zuurw** [comment]
Hi @HikwaMehluli Im going to make the Pull Request of the logo and logotype.
Who is this guy? Is making also a logo for you?
Can you please delete is comments and is name of this issue, I will apreciate that.

Do you have other projects to work? I can help if you need.

Greetings and enjoy your logo.

**Comment by zuurw** [comment]
I made de pull request, so now the work is done!

Best regards!

**Comment by HikwaMehluli** [comment]
Great.

**Comment by zuurw** [comment]
I'm sorry for bothering you again, but I wanted to ask if you please can remove the name of the other guy, I'd be very grateful for that.

Best Regards

**Comment by HikwaMehluli** [comment]
remove it from where?

Your profile is the one that is credited as contributor @zuurw

**Comment by zuurw** [comment]
You made this comment responding to this guy: "@nunojesus png, I have just updated and used @zuurw logo but needed him to do pull request so he gets his contributor status"

So Im asking if you can delete that, because I  print  the issues to add to my paper portfolio and I prefair to have all the converation only with the project owner.

But if you do not want to do that, it's no problem at all.

Beste Regards!
